// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIF9hjQoScxYw5VhvIHVZpd9RykCopfic',
    appId: '1:30877639638:web:0b1fc973941355e1d77a77',
    messagingSenderId: '30877639638',
    projectId: 'flutter-winterhacks-auth',
    authDomain: 'flutter-winterhacks-auth.firebaseapp.com',
    storageBucket: 'flutter-winterhacks-auth.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqoS4KTYwDkAhL76Jow1KjqPZDUOLPUoo',
    appId: '1:30877639638:android:86d5040a80cb56d8d77a77',
    messagingSenderId: '30877639638',
    projectId: 'flutter-winterhacks-auth',
    storageBucket: 'flutter-winterhacks-auth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEWIYcPge5D6wcEd9UMmuwIhQ0-2AEUMI',
    appId: '1:30877639638:ios:88a9ef1f6d7899dbd77a77',
    messagingSenderId: '30877639638',
    projectId: 'flutter-winterhacks-auth',
    storageBucket: 'flutter-winterhacks-auth.appspot.com',
    androidClientId: '30877639638-e67e3in6ltterfkdp2jia7jebkdvo705.apps.googleusercontent.com',
    iosClientId: '30877639638-o2b1cghp8i5g9gan1prrp1vf1bm49egd.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseWinterhacks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEWIYcPge5D6wcEd9UMmuwIhQ0-2AEUMI',
    appId: '1:30877639638:ios:d75f514081682e0ad77a77',
    messagingSenderId: '30877639638',
    projectId: 'flutter-winterhacks-auth',
    storageBucket: 'flutter-winterhacks-auth.appspot.com',
    androidClientId: '30877639638-e67e3in6ltterfkdp2jia7jebkdvo705.apps.googleusercontent.com',
    iosClientId: '30877639638-du3pkufau7td7fk5lkk15164jd5morv3.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseWinterhacks.RunnerTests',
  );
}
